services:
  api-service:
    image: ezemastro/ai_router:latest
    container_name: api-bun-app
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true